language: node_js
node_js:
- stable
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: YoW3e8LLIhMjhuky3N52paRRB0+pGSE7kXI6xM+V4nXuLrtQePKQ9uKz/Hl8mVBeihjwPhPCRPecqi2sXj2eTkmUyLkgf14qduwQzAiXag8m7q7VI5EacaOnhD7pTK/9MrtlaLeF8E/Uc3YkHTkvTmIfdoGV8U6L8GG+yg/bugFR5VqIS20X0Vxg04Tun+xvlxJGXNun9/DZ9aJixalB5N9tQi+WzpCZeyd92e86RSOWjY5GfLcjNvU1gBNlFYD8mC/++FnHtzsOeOxTu3MYq97GCs1oc3BeGlvkVnEeD9q3BPxyNwqSkxE//ea26KsApCM7kYbJUS2V8svnDsGWzzDISRWg2Lqo8cQ8NneJR0MBDfOiUCK3LIngbbdVfGmym52mDJDO8kZHGj84XjkQ7zhZpqP1GoJJDmgan5yt4QHMQzjP8e35mWrb8UeRS1yloALzTP+BvjeslmV57GVr62dSt88w1JYxPihsOFmMb+SqkA1SxwnvcXmQVgIauclGL0gfo4O9CPJCS30hDyttwFWWszmYr5USrA1HPFMWyMIS0lJBjdFyKHr27pGjDJgowJ9D7cAX8ljUQzqXKoncViy0EP1TglJ/l0oiiHwbnltYS20BOfbOTDllaM9135bep/vNy2/kgGQM6L4kOiC6I8LOlPy2dVGVTyLyAV7/D60=
    app: gentle-waters-43988