language: node_js
node_js:
- stable
script:
- heroku
- npm test
deploy:
  provider: heroku
  app: gentle-waters-43988
  api_key:
    secure: H7PmDSdq3F8yCog452hLV0ssnQ/MrMaF477cJ745uIEuiUPtJL29PNUzQmZXP+WILM4PZiOcnyaEULQHBK7N8TNSIyQaDTgJGCdoiOrCIFgFWglPf5iRBvFq2qKGFJaDeZFlOa+gfhQDyxnvJ068OP2ZuGsMkiXT1zXFuAWouE7y7iaafuzItMXHp2JTUBJazyKHJtL4TbCHRn2nLCTmxomr/uBCB5kThR65MK4iJlQTRbLKsZPdCIfz75w9fIAsneyi12taffQXXMLtj4M8eIfi/bG0Ccr2OiO9VO3TkitI0nYl5Yss8xlnvoX0cVMYRVgW6zHiaoor+2j26TKY/l81u6IwnD5Jm1JE3NPabaqdRsMfT/Ux4y/lRPO7qZ34J7sh+YLzLFcLMfIfJfQe9m8/c+te8L2gPbghDE818M0HciK9yZso2jlB00rangzPRGZMSqT2nm5/3YaeOWmRAaPjGMei5EtsFk3QYFk8ICNi/QAwpeb1apclkoNoP/bCqC5fHVi7C1fQwhthYVSvkyrPS73BzhYVIk1GRQ3ZGvJOydIr10oUjeaI/m1LtPy4fuB2eg9taX8H28klHl+HZf8mXrGsGCK/Pj/w5xCfTvtwu5xRZDZqAmYSJRkgA5OzrOQLaewCn+kaJ1owdJLsbFHxnYD0RavcPfFlDf7Y3uU=
